#!/bin/sh
#
# Track a remote branch
#
# Copyright (c) 2009 Daniel Schierbeck <daniel.schierbeck@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

USAGE="<remote> [<remote-branch>]"
LONG_USAGE="Track a remote branch"
SUBDIRECTORY_OK=Yes
OPTIONS_SPEC=

. "`git --exec-path`/git-sh-setup"

branch=`git symbolic-ref -q HEAD | sed "s!refs/heads/!!"`

if [ "$branch" = "" ]
then
  die "Make sure you're on a branch."
fi

remote=$1

if [ "$1" = "" ]
then
  die "You need to specify a remote."
fi

if [ "$2" = "" ]
then
  merge=$branch
else
  merge=$2
fi

git config branch.$branch.remote $remote
git config branch.$branch.merge refs/heads/$merge

echo "Tracking $remote/$merge"

exit 0
