#!/bin/sh
#
# Add the supplied patterns to the .gitignore file
#
# Copyright (c) 2009 Daniel Schierbeck <daniel.schierbeck@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

USAGE="<filepattern>..."
LONG_USAGE="Add file patterns to the .gitignore file"
SUBDIRECTORY_OK=Yes
OPTIONS_SPEC=
. git-sh-setup

if [ $# = 0 ]
then
  die "Please supply at least one file pattern"
fi

for var in "$@"
do
  echo "$var" >> .gitignore
done

exit 0
